---
name: CI & Deploy (Pages)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Install / Lint / Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Run linter (if present)
        run: npm run lint --if-present
      - name: Run tests (if present)
        run: npm test --if-present
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare site (copy src -> out)
        run: |
          if [ ! -d "src" ]; then
            echo "src/ directory not found" >&2
            exit 1
          fi
          rm -rf out || true
          mkdir out
          cp -r src/* out/
          # Copy root static files needed for PWA
          cp manifest.json out/ || true
          cp LICENSE out/ || true
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
      - name: Deploy
        uses: actions/deploy-pages@v1
